project-name: Console
source-files-pattern: locales/en/*.json
target-languages:
  - pt-BR
  - fr-FR
  - de-DE
workflows:
  pull-requests:
    translation-type: machine
    merge-policy: commit
  branches:
    - name: main
      translation-type: human
      merge-policy: pr
